export default {
    logo: require('../asset/icon/fire.png'),
    question: require('../asset/icon/question.png'),
    chat: require('../asset/icon/bubble-chat.png'),
    setting: require('../asset/icon/settings.png'),
    chatActive: require('../asset/icon/bubble-chat_active.png'),
    settingActive: require('../asset/icon/settings_active.png'),
    menu: require('../asset/icon/menu.png'),
    dots: require('../asset/icon/dots.png'),
    user: require('../asset/icon/user_profile.png'),
    user_active: require('../asset/icon/user_profile_active.png'),
    left_arrow_small: require('../asset/icon/left-arrow_small.png'),
    send: require('../asset/icon/send.png'),
    email: require('../asset/icon/email.png'),
    language: require('../asset/icon/language.png'),
    lock: require('../asset/icon/lock.png'),
    logout: require('../asset/icon/logout.png'),
    phone: require('../asset/icon/phone.png'),
    recycle: require('../asset/icon/recycle.png'),
    right_arrow: require('../asset/icon/right_arrow.png'),
    guest: require('../asset/icon/guest.png'),
    door: require('../asset/icon/door.png'),
    fingerprint: require('../asset/icon/fingerprint.png'),
    like: require('../asset/icon/like.png'),
    valentine: require('../asset/icon/valentine.png'),
    pencil: require('../asset/icon/pencil.png'),
    pencil_white: require('../asset/icon/pencil_white.png'),
};
